version: 2.1
orbs:
  heroku: circleci/heroku@1.0.0
workflows:
  heroku_deploy:
    jobs:
      - test
      - deploy

jobs:
  test:
    docker: circleci/python:3.7.3
    steps:
      - checkout
      - run:  echo "HELLO WORLD"

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
